entity_sets:
  paragraphs:
    - 2d_hot_spot
    - 2d_model_viewer
    - 3d_model_viewer
    - _d-model_viewer
    - accordion
    - accordion_item
    - accordion_with_fact_box
    - animated_text_with_image
    - animated_text_with_image_full_sc
    - annotation_banner
    - annotation_text
    - annotation_video
    - apprenticeship_matrix
    - article_items
    - author
    - author_details
    - banner_quick_links
    - bayer_map
    - calendar_archive
    - calendar_table
    - career_link
    - cluster_composition
    - cluster_composition_c
    - consent_disclaimers
    - contact
    - contact_block
    - contact_worldwide
    - content_with_sidebars
    - cta_button
    - download_bar
    - download_tool
    - easyxdm
    - event_calendar_block
    - event_location
    - events_block
    - events_list
    - fact_box
    - fact_callout
    - featured_banner
    - featured_card
    - featured_content_section
    - featured_contents
    - file_upload
    - financial_cards
    - financial_report
    - financial_report_download
    - flip
    - footer_section
    - footer_video
    - get_in_touch_block
    - grid_layout
    - headline_intro
    - hero_teaser
    - hero_teaser_group
    - hot_spot
    - html_editor
    - html_editor_fact_box
    - iframe
    - image
    - image_collage
    - image_comparison_slider
    - image_gallery
    - image_gallery_with_fact_box
    - image_overlay
    - image_wide
    - info_box
    - infographics
    - interactive_map
    - intrado_webcasts
    - ir_news_search_block
    - job_search
    - job_search_banner
    - jumbotron
    - latest_jobs
    - latest_news
    - link_list
    - links
    - list_links
    - list_links_dropdown
    - local_news_content
    - location
    - location_data
    - location_details
    - magazine_cluster_tabs
    - matrix_item
    - media
    - media_card
    - media_gallery
    - mega_menu
    - menu_image_block
    - menu_item
    - mini_banner
    - most_read_articles
    - news_list
    - news_overview_block
    - newsletter
    - newsletter_block
    - newsletter_subscription_button
    - one_step_disclaimer
    - patient_assistance_tool
    - pipeline
    - procurement_contact_block
    - product_block
    - product_cluster
    - product_override
    - products_list
    - profile_card
    - publications
    - question_and_answer
    - quick_links
    - quiz_banner
    - quote
    - quote_slider
    - quote_slider_item
    - read_more
    - related_contents
    - report_form
    - report_list
    - report_side_effect
    - search_box
    - section_introduction
    - share_infographic
    - sitemap
    - social_media_block
    - social_media_buttons
    - social_media_channels
    - social_media_share
    - stock_price
    - sub_location_details
    - tab
    - tab_item
    - tab_with_fact_box
    - table
    - table_items
    - tables
    - teaser_card
    - text
    - text_tile
    - text_with_image
    - text_with_image_fact_box
    - timeline_item
    - timeline_items
    - title
    - transparency_datagrid
    - two_step_disclaimer
    - two_step_disclaimer_item
    - video_carousel
    - video_playlist
    - video_playlist_item
    - visual_asset_item
    - visual_assets
    - vr_hot_spot
    - vr_viewer
  nodes:
    - content_page
    - country_page
    - event
    - landing_page
    - local_news
    - magazine
    - page
    - product
    - program
    - report
    - special_disclaimer
    - special_page
  media:
    - audio_file
    - image
    - video
    - video_file
  files:
    - audio
    - document
    - image
    - undefined
    - video
  taxonomy_terms:
    - application
    - category
    - contact
    - countries
    - event_category
    - feature_listing_keywords
    - field_of_activity
    - keymatch
    - languages
    - magazine_context
    - map
    - media_tags
    - media_tags_list
    - news_area
    - news_context
    - news_topics
    - partner
    - product_context
    - product_import
    - region
    - report_category
    - report_side_effect_languages
    - social_channels
    - social_media
    - sub_hub_controls
    - tags
    - therapeutic_area
    - topics
    - url_slug
